forum/urls.py
from django.urls import path
from . import views


app_name = "forum"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<topic>/", views.ForumView.as_view(), name="forum"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# 15で追加
from django.conf.urls.static import static
# 17で追加
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
    # path("forum/", include("forum.urls")),
    path('accounts/', include('allauth.urls')), # 追加
]

# 17で追加
urlpatterns += i18n_patterns(
    path("forum/", include("forum.urls")),
    path("", include("forum.urls")),
)
#↑ここまで

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

# 15で追加
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path  # path() 関数をインポート

from . import views  # ビュー関数を登録するため、views.py をインポート

app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("ensyu<int:question_id>/", views.ensyu, name="ensyu"),
    path("<int:question_id>/resets/", views.resets, name="resets"),
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)  # 質問の内容
    pub_date = models.DateTimeField("date published")  # 作成日時
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # どの質問に対する回答か
    choice_text = models.CharField(max_length=200)  # 回答の選択肢
    votes = models.IntegerField(default=0)  # 投票数
    def __str__(self):
        return self.choice_text


class Example(models.Model):
    name = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    price = models.IntegerField(default=0)
    choices = models.ManyToManyField(Choice)  # 多対多の関係、中間テーブル（example_choices）を自動作成
    def __str__(self):
        return self.name

polls/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect  # redirect を追加

from .models import Question, Example, Choice  # Choice を追加


def index(request):
    # 新しいものから 5 個
    latest_question_list = Question.objects.all()
    context = {
        "latest_question_list": latest_question_list,
    }
    return render(request, "polls/index.html", context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        "question": question,
    }
    return render(request, "polls/detail.html", context)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        "question": question,
    }
    return render(request, "polls/results.html", context)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])  # pk が POST の choice の値と等しいものがあれば、データベースから取得する
    except (KeyError, Choice.DoesNotExist):  # 例外処理
        # フォームを再度表示する
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 10
        selected_choice.save()
        # POST データを正常に処理した後は、redirect() を返します。これにより、ユーザーが「戻る」ボタンを押した場合にデータが 2 回投稿されるのを防ぎます。
        return redirect('polls:results', question.id)


def resets(request, question_id):
    choices_to_reset = request.POST.getlist('resets')
    for choice_id in choices_to_reset:
        choice = get_object_or_404(Choice, pk=choice_id)
        choice.votes = 0  # 投票数をリセット
        choice.save()  # データベースに保存
        # POST データを正常に処理した後は、redirect() を返します。これにより、ユーザーが「戻る」ボタンを押した場合にデータが 2 回投稿されるのを防ぎます。
    return redirect('polls:results', question_id)
    

def ensyu(request, question_id):
    example_data = get_object_or_404(Example, pk=question_id)
    choices_data = example_data.choices.all()
    context = {
        "example": example_data,
        "choices_list": choices_data,
    }
    return render(request, "polls/ensyu.html", context)

polls/templates/polls/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Polls アプリケーション</title>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/css/index.css' %}" />
    </head>
    <body>
        <form action="{% url 'polls:vote' question.id %}" method="POST">  {# URL polls:vote に、question の id と form での処理（POST）を渡す #}
            {% csrf_token %}  {# CSRF 対策（後に説明します）#}
            <div class="cp_ipradio">
                <h1>{{ question.question_text }}</h1>
        
                {% if error_message %}  {# もしエラーがあれば #}
                    <p><strong>{{ error_message }}</strong></p>  {# エラーを表示する #}
                {% endif %}
        
                {% for choice in question.choice_set.all %}  {# question の choice の数だけループする #}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">  {# ラジオボタン #}
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            </div>
            <input type="submit" value="Vote" class="btn-flat-border">
        </form>
        <br>
        <form action="{% url 'polls:resets' question.id %}" method="POST">
            {% csrf_token %}
            <div>
                {% for choice in question.choice_set.all %}
                    <input type="checkbox" name="resets" id="resets{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="resets{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            </div>
            <input type="submit" value="Resets">
        </form>
        <br>
        <a href="{% url 'polls:index' %}">他の質問に投票する</a>
        <br>
        <a href="{% url 'forum:index' %}">掲示板アプリに移動する</a>
    </body>
</html>

polls/templates/polls/ensyu.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>Polls アプリケーション</title>
    </head>
    <body>
        <h1>{{ example.name }}さん、ご注文ありがとうございます。</h1>
        <h1>注文：{{ example.item }}</h1>
        <h1>価格：{{ example.price }}円</h1>
        <br>
        <h1>⬇️{{ example.name }}さんの選択項目</h1>
        {% for choice in choices_list %}
            <h2>・{{ choice.choice_text }}</h2>
        {% endfor %}
    </body>
</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Polls アプリケーション</title>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/css/index.css' %}" />
    </head>
    <body>
        <h1>投票アプリ</h1>
        {% if latest_question_list %}
            <ul class="container">
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
        <br>
        <a href="{% url 'forum:index' %}">掲示板アプリに移動する</a>
    </body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>Polls アプリケーション</title>
    </head>
    <body>
        <h1>{{ question.question_text }}</h1>
        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }}：{{ choice.votes }} 票</li>
        {% endfor %}
        </ul>        
        <a href="{% url 'polls:detail' question.id %}">もう一度投票する</a>
        <br>
        <a href="{% url 'polls:index' %}">他の質問に投票する</a>
        <br>
        <a href="{% url 'forum:index' %}">掲示板アプリに移動する</a>
    </body>
</html>